# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Xuan Cuong Pham
tagline:          'Lecturer at School of Information and Communication, Water Resources University, Ha Noi, Viet Nam'
description:      'My Blog'
url:              http://lanyon.getpoole.com

author:
  name:           'CuongPX'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
