# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            CuongPX
tagline:          'A Jekyll theme'
description:      'My Blog'
url:              http://lanyon.getpoole.com

author:
  name:           'Cuong PX'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
